HW 1.2

1.2.4  Eigenvalues and Eigenvectors

In [47]:
import numpy as np
np.random.seed(12)

# Create square matrix A
A = np.random.randint(-4,5,(3,3))

# Find eigenvalues of A
eval,evec = np.linalg.eig(A)
for i in range(len(eval)):
    print(f"Eigenvalue {i+1} = {eval[i]} with eigenvector {evec[i]}")


Eigenvalue 1 = 3.753596191098105 with eigenvector [-0.32227737  0.69883303  0.54221232]
Eigenvalue 2 = 0.7585437555790957 with eigenvector [0.64827416 0.57385345 0.7659311 ]
Eigenvalue 3 = -3.512139946677203 with eigenvector [-0.68983905 -0.42699486  0.34547845]


The eig() function finds the potential eigenvalues and vectors for a matrix A. As seen in the results, there are at most 3 eigenvalues for our square matrix with dimension 3. 

In [56]:
# Diagonalization of A
D = np.diag(eval)
P = np.array(evec)

A_diag = P@D@np.linalg.inv(P)
print(A)
print('\n',A_diag)

A_diag_orthogonal = P@D@np.matrix.transpose(P)

print('\n',A_diag_orthogonal)

[[ 2 -3 -2]
 [-1 -1 -4]
 [ 2 -3  0]]

 [[ 2.00000000e+00 -3.00000000e+00 -2.00000000e+00]
 [-1.00000000e+00 -1.00000000e+00 -4.00000000e+00]
 [ 2.00000000e+00 -3.00000000e+00 -1.31309464e-15]]

 [[-0.27224191 -1.93860174 -0.04975376]
 [-1.93860174 -0.23312008 -2.79385097]
 [-0.04975376 -2.79385097  1.50536199]]


As shown by the results, A is diagonalizable, as A approximately equals the diagonal form of A = PDP^-1. However, we can see that A is not orthogonally diagonalizable, as A is not equal to PDP^T.

In [64]:
# Create symmetric matrix B
B = np.array([[4,-1,4],[-1,3,-5],[4,-5,0]])  

# Find eigenvalues/vectors and diagonalization of B
evalB,evecB = np.linalg.eig(B)
D = np.diag(evalB)
P = np.array(evecB)

# Calculate B using Diagonalization
B_diag = P@D@np.linalg.inv(P)
B_diag_ortho = P@D@np.matrix.transpose(P)

print(B,'\n\n',B_diag,'\n\n',B_diag_ortho)

[[ 4 -1  4]
 [-1  3 -5]
 [ 4 -5  0]] 

 [[ 4.0000000e+00 -1.0000000e+00  4.0000000e+00]
 [-1.0000000e+00  3.0000000e+00 -5.0000000e+00]
 [ 4.0000000e+00 -5.0000000e+00  4.2737951e-16]] 

 [[ 4.00000000e+00 -1.00000000e+00  4.00000000e+00]
 [-1.00000000e+00  3.00000000e+00 -5.00000000e+00]
 [ 4.00000000e+00 -5.00000000e+00 -4.63755039e-17]]


Now we can see that both methods equaled the matrix B. Thus, B = PDP^-1 = PDP^T, so our matrix B is orthogonally diagonalizable.

In [63]:
# Test symmetry of B
B_trans = np.matrix.transpose(B_diag_ortho)
print(B_trans)

[[ 4.00000000e+00 -1.00000000e+00  4.00000000e+00]
 [-1.00000000e+00  3.00000000e+00 -5.00000000e+00]
 [ 4.00000000e+00 -5.00000000e+00 -4.63755039e-17]]


Now we can confirm that our matrix is symmetric, using the theorem that if B is orthogonally diagonalizable, B = B^T.